# Book settings
title:
author: World Bank
logo: docs/images/logo.png
only_build_toc_files: true

repository:
  url: https://github.com/twisha-shah99/cs7461-team29-mlProject/
  branch: main

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: true
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://github.com/twisha-shah99/cs7461-team29-mlProject/
  extra_footer: |
    <div>
        <b>All content (unless otherwise specified) is subject to the <a href="https://raw.githubusercontent.com/worldbank/template/main/LICENSE">World Bank Master Community License Agreement.</a></b>
    </div>
#######################################################################################
# Execution settings
execute:
  execute_notebooks: off
  allow_errors: true
  exclude_patterns:
    - notebooks/*.ipynb

#######################################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"
